<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentScheduler" Version="5.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EList.Filestorage.BackgroundUploader\EList.Filestorage.BackgroundWorker.csproj" />
    <ProjectReference Include="..\EList.Filestorage.Core\EList.Filestorage.Core.csproj" />
    <ProjectReference Include="..\EList.Filestorage.Data.Linq2db\EList.Filestorage.Data.Linq2db.csproj" />
  </ItemGroup>

</Project>
